export const testCardData = [
  {
    id: 1,
    theme: "Web Design",
    title: "Разработка макета",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 2,
    theme: "Copywriting",
    title: "Создание компонентов",
    date: "02.11.23",
    status: "Нужно сделать",
  },
  {
    id: 3,
    theme: "Research",
    title: "Настройка API",
    date: "05.11.23",
    status: "В работе",
  },
  {
    id: 4,
    theme: "Testing",
    title: "Проверка логики входа",
    date: "07.11.23",
    status: "Тестирование",
  },
  {
    id: 5,
    theme: "DevOps",
    title: "Деплой проекта",
    date: "10.11.23",
    status: "Готово",
  },
  {
    id: 6,
    theme: "Web Design",
    title: "Редизайн главной страницы",
    date: "12.11.23",
    status: "Нужно сделать",
  },
  {
    id: 7,
    theme: "Frontend",
    title: "Анимации интерфейса",
    date: "14.11.23",
    status: "В работе",
  },
  {
    id: 8,
    theme: "Backend",
    title: "Обработка ошибок",
    date: "16.11.23",
    status: "Тестирование",
  },
  {
    id: 9,
    theme: "Testing",
    title: "Тестирование API",
    date: "18.11.23",
    status: "Готово",
  },
  {
    id: 10,
    theme: "DevOps",
    title: "Настройка CI/CD",
    date: "20.11.23",
    status: "Готово",
  },
];
